# Spring Boot
spring.application.name=devtools-engine

# Actuator & Prometheus
management.endpoints.web.exposure.include=prometheus,health

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=devtools-group

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/devtools

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
